//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infraestructura {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    internal sealed partial class SETT : global::System.Configuration.ApplicationSettingsBase {
        
        private static SETT defaultInstance = ((SETT)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new SETT())));
        
        public static SETT Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.0.200,1434;initial catalog=GTIntegration_Sebas;user id=gt;pas" +
            "sword=gt")]
        public string Conexion {
            get {
                return ((string)(this["Conexion"]));
            }
            set {
                this["Conexion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.200/WSUNOEE/WSUNOEE.Asmx?WSDL")]
        public string InfraWSIESA {
            get {
                return ((string)(this["InfraWSIESA"]));
            }
            set {
                this["InfraWSIESA"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.200/GTIntegration_Sebas/ServiciosWeb/wsGenerarPlano.asmx?WSDL")]
        public string InfraGTI {
            get {
                return ((string)(this["InfraGTI"]));
            }
            set {
                this["InfraGTI"] = value;
            }
        }
    }
}
